apiVersion: v1
kind: ConfigMap
metadata:
  name: descheduler
data:
  policy.yaml: |
    apiVersion: "descheduler/v1alpha2"
    kind: "DeschedulerPolicy"
    profiles:
      - name: ProfileName
        pluginConfig:
        - name: "RemoveDuplicates"
          args:
            excludeOwnerKinds:
              - "ReplicaSet"
        plugins:
          balance:
            enabled:
              - "RemoveDuplicates"